INSERT INTO usuario VALUES (DEFAULT, "igorfratel", senha!!!, '2018-05-11 14:53:00');
INSERT INTO usuario VALUES (DEFAULT, "feulo", senha!!!, '2018-05-11 14:53:00');
INSERT INTO usuario VALUES (DEFAULT, "caio", senha!!!, '2018-05-11 14:53:00');
INSERT INTO usuario VALUES (DEFAULT, "pablo", senha!!!, '2018-05-11 14:53:00');
INSERT INTO usuario VALUES (DEFAULT, "manobrown10", senha!!!, '2018-05-11 14:53:00');

INSERT INTO pessoa VALUES (DEFAULT,);
INSERT INTO pessoa VALUES (DEFAULT,);
INSERT INTO pessoa VALUES (DEFAULT,);
INSERT INTO pessoa VALUES (DEFAULT,);
INSERT INTO pessoa VALUES (DEFAULT,);

INSERT INTO perfil VALUES (DEFAULT, "adm", "perfil_admin");
INSERT INTO perfil VALUES (DEFAULT, "alu", "perfil_aluno");
INSERT INTO perfil VALUES (DEFAULT, "pro", "perfil_prof");
INSERT INTO perfil VALUES (DEFAULT, "gue", "perfil_guest");
INSERT INTO perfil VALUES (DEFAULT, "mas", "perfil_master");

INSERT INTO servico VALUES (DEFAULT, );
INSERT INTO servico VALUES (DEFAULT, );
INSERT INTO servico VALUES (DEFAULT, );
INSERT INTO servico VALUES (DEFAULT, );
INSERT INTO servico VALUES (DEFAULT, );

INSERT INTO aluno VALUES (DEFAULT, "9793565", 2016, "V", (SELECT id_pessoa from pessoa WHERE atributo="blablabla"));
INSERT INTO aluno VALUES (DEFAULT, "123456", 2016, "V");
INSERT INTO aluno VALUES (DEFAULT, "9791234", 2016, "V");
INSERT INTO aluno VALUES (DEFAULT, "9794561", 2016, "E");
INSERT INTO aluno VALUES (DEFAULT, "0000000", 1975, "V");


INSERT INTO professor VALUES (DEFAULT,);
INSERT INTO professor VALUES (DEFAULT,);
INSERT INTO professor VALUES (DEFAULT,);
INSERT INTO professor VALUES (DEFAULT,);
INSERT INTO professor VALUES (DEFAULT,);

INSERT INTO disciplina VALUES (DEFAULT,);
INSERT INTO disciplina VALUES (DEFAULT,);
INSERT INTO disciplina VALUES (DEFAULT,);
INSERT INTO disciplina VALUES (DEFAULT,);
INSERT INTO disciplina VALUES (DEFAULT,);

INSERT INTO modulo VALUES (DEFAULT,);
INSERT INTO modulo VALUES (DEFAULT,);
INSERT INTO modulo VALUES (DEFAULT,);
INSERT INTO modulo VALUES (DEFAULT,);
INSERT INTO modulo VALUES (DEFAULT,);

INSERT INTO trilha VALUES (DEFAULT,);
INSERT INTO trilha VALUES (DEFAULT,);
INSERT INTO trilha VALUES (DEFAULT,);
INSERT INTO trilha VALUES (DEFAULT,);
INSERT INTO trilha VALUES (DEFAULT,);

INSERT INTO tem_perfil VALUES (DEFAULT,);
INSERT INTO tem_perfil VALUES (DEFAULT,);
INSERT INTO tem_perfil VALUES (DEFAULT,);
INSERT INTO tem_perfil VALUES (DEFAULT,);
INSERT INTO tem_perfil VALUES (DEFAULT,);

INSERT INTO tem_permissao VALUES (DEFAULT,);
INSERT INTO tem_permissao VALUES (DEFAULT,);
INSERT INTO tem_permissao VALUES (DEFAULT,);
INSERT INTO tem_permissao VALUES (DEFAULT,);
INSERT INTO tem_permissao VALUES (DEFAULT,);

INSERT INTO ministra VALUES (DEFAULT,);
INSERT INTO ministra VALUES (DEFAULT,);
INSERT INTO ministra VALUES (DEFAULT,);
INSERT INTO ministra VALUES (DEFAULT,);
INSERT INTO ministra VALUES (DEFAULT,);

INSERT INTO compoe_modulo VALUES (DEFAULT,);
INSERT INTO compoe_modulo VALUES (DEFAULT,);
INSERT INTO compoe_modulo VALUES (DEFAULT,);
INSERT INTO compoe_modulo VALUES (DEFAULT,);
INSERT INTO compoe_modulo VALUES (DEFAULT,);

INSERT INTO compoe_trilha VALUES (DEFAULT,);
INSERT INTO compoe_trilha VALUES (DEFAULT,);
INSERT INTO compoe_trilha VALUES (DEFAULT,);
INSERT INTO compoe_trilha VALUES (DEFAULT,);
INSERT INTO compoe_trilha VALUES (DEFAULT,);

INSERT INTO cursa VALUES (DEFAULT,);
INSERT INTO cursa VALUES (DEFAULT,);
INSERT INTO cursa VALUES (DEFAULT,);
INSERT INTO cursa VALUES (DEFAULT,);
INSERT INTO cursa VALUES (DEFAULT,);

INSERT INTO plano VALUES (DEFAULT,);
INSERT INTO plano VALUES (DEFAULT,);
INSERT INTO plano VALUES (DEFAULT,);
INSERT INTO plano VALUES (DEFAULT,);
INSERT INTO plano VALUES (DEFAULT,);
